function data = nv3_synthetic_mixed_delta_wye_case(config, opts)
%NV3_SYNTHETIC_MIXED_DELTA_WYE_CASE Parallel delta and wye black-box load.
%
% The terminal voltage is generated by a current-driven wye-series branch.
% A delta-parallel branch is then connected to the same terminal voltages and
% its line currents are added.  The resulting terminal behavior is a genuine
% composite black box, not one of the pure candidate topologies.

if nargin < 1 || isempty(config)
    config = nv3_default_config();
end
if nargin < 2
    opts = struct();
end

fs = nv3_get_option(opts, 'fs', config.fs);
f0 = nv3_get_option(opts, 'f0', config.f0);
duration = nv3_get_option(opts, 'duration', config.duration);
noiseSnrDb = nv3_get_option(opts, 'noiseSnrDb', config.noiseSnrDb);
seed = nv3_get_option(opts, 'randomSeed', config.randomSeed);

wyeTruth = nv3_get_option(opts, 'wyeTruth', default_wye_truth());
deltaTruth = complete_delta_truth(nv3_get_option(opts, 'deltaTruth', ...
    default_delta_truth()));
iaComponents = nv3_get_option(opts, 'iaComponents', ...
    [10.0, 1, 0.10; 0.90, 5, -0.30; 0.45, 7, 1.20]);
ibComponents = nv3_get_option(opts, 'ibComponents', ...
    [8.0, 1, -2.05; 0.70, 5, 0.85; 0.25, 7, -1.40]);

wyeData = nv3_synthetic_wye_series_case(config, struct( ...
    'model', 'wye_series_rlc', ...
    'truth', wyeTruth, ...
    'iaComponents', iaComponents, ...
    'ibComponents', ibComponents, ...
    'noiseSnrDb', Inf));

t = wyeData.t;
vab = wyeData.clean.vab;
vbc = wyeData.clean.vbc;
vca = wyeData.clean.vca;
harmonics = unique([iaComponents(:, 2); ibComponents(:, 2)]).';
vabFit = nv3_harmonic_fit(vab, t, f0, harmonics, struct('maxOrder', 1));
vbcFit = nv3_harmonic_fit(vbc, t, f0, harmonics, struct('maxOrder', 1));
vcaFit = nv3_harmonic_fit(vca, t, f0, harmonics, struct('maxOrder', 1));

iabDelta = delta_branch_current(deltaTruth, 'ab', vabFit.values{1}, ...
    vabFit.primitive, vabFit.values{2});
ibcDelta = delta_branch_current(deltaTruth, 'bc', vbcFit.values{1}, ...
    vbcFit.primitive, vbcFit.values{2});
icaDelta = delta_branch_current(deltaTruth, 'ca', vcaFit.values{1}, ...
    vcaFit.primitive, vcaFit.values{2});

iaDelta = iabDelta - icaDelta;
ibDelta = ibcDelta - iabDelta;
icDelta = icaDelta - ibcDelta;

ia = wyeData.clean.ia + iaDelta;
ib = wyeData.clean.ib + ibDelta;
ic = wyeData.clean.ic + icDelta;

[vabN, vbcN, vcaN, iaN, ibN, icN] = add_noise(seed, noiseSnrDb, ...
    vab, vbc, vca, ia, ib, ic);

data = struct();
data.model = 'mixed_delta_wye';
data.label = 'Three-wire mixed delta GLC + wye series RLC';
data.fs = fs;
data.f0 = f0;
data.t = (0:round(duration * fs) - 1).' / fs;
data.vab = vabN;
data.vbc = vbcN;
data.vca = vcaN;
data.ia = iaN;
data.ib = ibN;
data.ic = icN;
data.clean = struct('vab', vab, 'vbc', vbc, 'vca', vca, ...
    'ia', ia, 'ib', ib, 'ic', ic, ...
    'iaWye', wyeData.clean.ia, 'ibWye', wyeData.clean.ib, ...
    'icWye', wyeData.clean.ic, ...
    'iaDelta', iaDelta, 'ibDelta', ibDelta, 'icDelta', icDelta, ...
    'iabDelta', iabDelta, 'ibcDelta', ibcDelta, 'icaDelta', icaDelta);
data.truth = struct('wye', wyeTruth, 'delta', deltaTruth);
data.power = struct('measured', three_wire_power(vabN, vbcN, iaN, ibN), ...
    'clean', three_wire_power(vab, vbc, ia, ib));
data.currentComponents = struct('ia', iaComponents, 'ib', ibComponents);
data.noiseSnrDb = noiseSnrDb;

end

function truth = default_wye_truth()
truth = struct('Ra', 0.50, 'Rb', 1.20, 'Rc', 0.80, ...
    'La', 5.0e-3, 'Lb', 8.0e-3, 'Lc', 3.0e-3, ...
    'Gammaa', 1 / 450e-6, 'Gammab', 1 / 320e-6, ...
    'Gammac', 1 / 680e-6);
truth.Ca = 1 / truth.Gammaa;
truth.Cb = 1 / truth.Gammab;
truth.Cc = 1 / truth.Gammac;
end

function truth = default_delta_truth()
truth = struct('Gab', 1 / 80, 'Gbc', 1 / 115, 'Gca', 1 / 70, ...
    'Gammaab', 1 / 0.22, 'Gammabc', 1 / 0.30, 'Gammaca', 1 / 0.18, ...
    'Cab', 18e-6, 'Cbc', 12e-6, 'Cca', 22e-6);
end

function truth = complete_delta_truth(truth)
if ~isfield(truth, 'Rab') && isfield(truth, 'Gab')
    truth.Rab = 1 / truth.Gab;
end
if ~isfield(truth, 'Rbc') && isfield(truth, 'Gbc')
    truth.Rbc = 1 / truth.Gbc;
end
if ~isfield(truth, 'Rca') && isfield(truth, 'Gca')
    truth.Rca = 1 / truth.Gca;
end
if ~isfield(truth, 'Lab') && isfield(truth, 'Gammaab')
    truth.Lab = 1 / truth.Gammaab;
end
if ~isfield(truth, 'Lbc') && isfield(truth, 'Gammabc')
    truth.Lbc = 1 / truth.Gammabc;
end
if ~isfield(truth, 'Lca') && isfield(truth, 'Gammaca')
    truth.Lca = 1 / truth.Gammaca;
end
end

function i = delta_branch_current(truth, branch, v, q, dv)
i = truth.(['G' branch]) * v + truth.(['Gamma' branch]) * q + ...
    truth.(['C' branch]) * dv;
end

function p = three_wire_power(vab, vbc, ia, ib)
p = vab(:) .* ia(:) + vbc(:) .* (ia(:) + ib(:));
end

function varargout = add_noise(seed, snrDb, varargin)
rng(seed);
varargout = cell(size(varargin));
for idx = 1:numel(varargin)
    x = varargin{idx};
    if isfinite(snrDb)
        sigma = sqrt(mean(x(:) .^ 2)) * 10 ^ (-snrDb / 20);
        varargout{idx} = x + sigma * randn(size(x));
    else
        varargout{idx} = x;
    end
end
end
