function recommendation = sp1_select_candidate_recommendation(candidates, opts)
%SP1_SELECT_CANDIDATE_RECOMMENDATION Select physical model recommendation.

if nargin < 2
    opts = struct();
end
bhImprovementFactor = nv3_get_option(opts, 'bhImprovementFactor', 0.50);
ltiEquivalenceFactor = nv3_get_option(opts, 'ltiEquivalenceFactor', 1.5);
ltiEquivalenceAbsTol = nv3_get_option(opts, 'ltiEquivalenceAbsTol', 2e-3);
accepted = candidates.Accepted > 0;
idxSwitching = find(strcmp(candidates.Family, 'switching') & accepted);
idxFlux = find(strcmp(candidates.Candidate, 'flux_curve'), 1);
idxBh = find(strcmp(candidates.Candidate, 'bh_loop'), 1);
idxLti = find(strcmp(candidates.Family, 'lti_windowed') & accepted);

if ~isempty(idxSwitching)
    [~, bestLocal] = min(candidates.ResidualOrScore(idxSwitching));
    idx = idxSwitching(bestLocal);
elseif ~isempty(idxLti)
    [~, bestLocal] = min(candidates.ResidualOrScore(idxLti));
    idx = idxLti(bestLocal);
    closeLti = idxLti(candidates.ResidualOrScore(idxLti) <= ...
        max(candidates.ResidualOrScore(idx) * ltiEquivalenceFactor, ...
        candidates.ResidualOrScore(idx) + ltiEquivalenceAbsTol));
    if numel(closeLti) > 1
        recommendation = lti_equivalence_recommendation(candidates, ...
            closeLti, idx, ltiEquivalenceFactor);
        return;
    end
elseif is_accepted(candidates, idxBh) && ...
        (~is_accepted(candidates, idxFlux) || ...
        candidates.ResidualOrScore(idxBh) < ...
        bhImprovementFactor * candidates.ResidualOrScore(idxFlux))
    idx = idxBh;
elseif is_accepted(candidates, idxFlux)
    idx = idxFlux;
elseif any(accepted)
    idx = find(accepted, 1, 'first');
else
    idx = [];
end

if ~isempty(idx)
    recommendation = struct('model', candidates.Candidate{idx}, ...
        'family', candidates.Family{idx}, ...
        'physicalMeaning', candidates.PhysicalMeaning{idx}, ...
        'parameters', candidates.Parameters{idx}, ...
        'reason', candidates.Reason{idx}, ...
        'decision', 'accepted_by_physical_selection');
else
    [~, idx] = max(candidates.Confidence);
    recommendation = struct('model', 'needs_segmentation_or_new_model', ...
        'family', 'outside_library', ...
        'physicalMeaning', ...
        'topology may be switching, outside current library, or poorly excited', ...
        'parameters', candidates.Parameters{idx}, ...
        'reason', candidates.Reason{idx}, ...
        'decision', 'no_candidate_passed');
end

end

function tf = is_accepted(candidates, idx)
tf = ~isempty(idx) && candidates.Accepted(idx) > 0;
end

function recommendation = lti_equivalence_recommendation(candidates, closeLti, ...
    bestIdx, equivalenceFactor)
names = candidates.Candidate(closeLti);
items = cell(numel(closeLti), 1);
for k = 1:numel(closeLti)
    items{k} = sprintf('%s: %s', candidates.Candidate{closeLti(k)}, ...
        candidates.Parameters{closeLti(k)});
end
recommendation = struct('model', 'lti_equivalent_family', ...
    'family', 'lti_windowed', ...
    'physicalMeaning', sprintf( ...
        'terminally compatible LTI energetic equivalents: %s', ...
        strjoin(names, ', ')), ...
    'parameters', strjoin(items, ' | '), ...
    'reason', sprintf(['%d LTI candidates accepted within residual factor ' ...
        '%.3g of best %s (best residual %.3g)'], ...
        numel(closeLti), equivalenceFactor, candidates.Candidate{bestIdx}, ...
        candidates.ResidualOrScore(bestIdx)), ...
    'decision', 'accepted_lti_equivalence_family');
end
