function candidate = sp1_candidate_switching_affine_rl(data, config, opts)
%SP1_CANDIDATE_SWITCHING_AFFINE_RL Candidate wrapper for ON/OFF LTI models.
%
% Historical name kept for API compatibility.  The wrapped implementation now
% tests switched_R, switched_RL, switched_RC, and switched_RLC ON-state
% candidates and returns the best accepted canonical switched model.

if nargin < 3
    opts = struct();
end

method = sp1_characterize_switching_load(data, config, opts);

candidate = sp1_candidate_result(struct( ...
    'Name', method.model, ...
    'Family', 'switching', ...
    'PhysicalMeaning', method.physicalMeaning, ...
    'Accepted', method.accepted, ...
    'Confidence', method.confidence, ...
    'Coverage', method.summary.OnCoverage, ...
    'ResidualOrScore', method.summary.MedianResidual, ...
    'StabilityCV', method.summary.StabilityCV, ...
    'Complexity', method.summary.Complexity + 1, ...
    'Parameters', method.parameters, ...
    'Reason', method.reason, ...
    'Method', method, ...
    'Diagnostics', struct('offCoverage', method.summary.OffCoverage, ...
    'transitionCoverage', method.summary.TransitionCoverage, ...
    'regime', method.regime.Label, ...
    'eventsPerCycle', method.regime.EventsPerCycle)));

end
