function candidate = sp1_candidate_lti_capacitor(data, config, opts, decisionOpts)
%SP1_CANDIDATE_LTI_CAPACITOR Candidate wrapper for pure capacitor.

if nargin < 3
    opts = struct();
end
if nargin < 4
    decisionOpts = struct();
end

method = sp1_identify_windowed_capacitor(data, config, opts);
W = method.windows;
valid = W.Valid > 0;
stabilityCV = sp1_robust_cv(W.C(valid));

coverageGate = nv3_get_option(decisionOpts, 'coverageGate', 0.80);
residualGate = nv3_get_option(decisionOpts, 'capacitorResidualGate', ...
    nv3_get_option(decisionOpts, 'residualGate', 2e-2));
stabilityGate = nv3_get_option(decisionOpts, 'stabilityGate', 0.15);

coverageOk = method.summary.ValidCoverage >= coverageGate;
residualOk = method.summary.MedianEquationResidual <= residualGate;
stableOk = stabilityCV <= stabilityGate;
accepted = coverageOk && residualOk && stableOk;
confidence = mean([double(coverageOk), double(residualOk), double(stableOk)]);
reason = sprintf(['coverage %.2f, equation residual %.3g, ' ...
    'power residual %.3g, stabilityCV %.3g'], ...
    method.summary.ValidCoverage, method.summary.MedianEquationResidual, ...
    method.summary.MedianPowerResidual, stabilityCV);
parameters = sprintf('C=%.6g F', method.summary.MedianC);

candidate = sp1_candidate_result(struct( ...
    'Name', 'lti_capacitor', ...
    'Family', 'lti_windowed', ...
    'PhysicalMeaning', 'pure capacitor: i = C dv/dt', ...
    'Accepted', accepted, ...
    'Confidence', confidence, ...
    'Coverage', method.summary.ValidCoverage, ...
    'ResidualOrScore', method.summary.MedianEquationResidual, ...
    'StabilityCV', stabilityCV, ...
    'Complexity', 1, ...
    'Parameters', parameters, ...
    'Reason', reason, ...
    'Method', method, ...
    'Diagnostics', struct('validWindows', sum(valid), ...
    'windowCount', height(W), ...
    'medianPowerResidual', method.summary.MedianPowerResidual)));

end
