function candidate = sp1_candidate_bh_loop(data, opts, decisionOpts)
%SP1_CANDIDATE_BH_LOOP Candidate wrapper for hysteretic B-H loop.

if nargin < 2
    opts = struct();
end
if nargin < 3
    decisionOpts = struct();
end

method = sp1_identify_bh_loop_parameters(data, opts);
residualGate = nv3_get_option(decisionOpts, 'bhResidualGate', 2e-2);
closureGate = nv3_get_option(decisionOpts, 'bhClosureGate', 0.05);

residualOk = method.residual <= residualGate;
passiveOk = method.R >= 0 && method.L0 > 0 && method.hysteresisCurrent >= 0;
closureOk = method.closure <= closureGate;
preconditioningOk = method.preconditioning.Credible;
accepted = residualOk && passiveOk && closureOk && preconditioningOk;
confidence = mean([double(residualOk), double(passiveOk), ...
    double(closureOk), double(preconditioningOk)]);
reason = sprintf(['residual %.3g, closure %.3g, R %.4g, L0 %.4g, ' ...
    'precondition %s'], method.residual, method.closure, method.R, ...
    method.L0, method.preconditioning.Reason);
parameters = sprintf(['R=%.6g ohm, L0=%.6g H, k3=%.6g, h=%.6g A, ' ...
    'v0=%.3g, i0=%.3g'], method.R, method.L0, ...
    method.saturationCubic, method.hysteresisCurrent, ...
    method.preconditioning.VOffset, method.preconditioning.IOffset);

candidate = sp1_candidate_result(struct( ...
    'Name', 'bh_loop', ...
    'Family', 'hysteretic_storage', ...
    'PhysicalMeaning', 'hysteretic magnetic loop', ...
    'Accepted', accepted, ...
    'Confidence', confidence, ...
    'Coverage', NaN, ...
    'ResidualOrScore', method.residual, ...
    'StabilityCV', NaN, ...
    'Complexity', 4, ...
    'Parameters', parameters, ...
    'Reason', reason, ...
    'Method', method, ...
    'Diagnostics', struct('closure', method.closure, ...
    'magneticLossPerCycle', method.magneticLossPerCycle, ...
    'preconditioning', method.preconditioning)));

end
