function candidate = sp1_candidate_flux_curve(data, config, opts, decisionOpts)
%SP1_CANDIDATE_FLUX_CURVE Candidate wrapper for lambda=f(i).

if nargin < 3
    opts = struct();
end
if nargin < 4
    decisionOpts = struct();
end

method = sp1_identify_flux_curve(data, config, opts);
scoreGate = nv3_get_option(decisionOpts, 'fluxScoreGate', 5e-2);
conditionGate = nv3_get_option(decisionOpts, 'fluxConditionGate', 1e8);

scoreOk = method.score <= scoreGate;
conditionOk = isfinite(method.basisCondition) && ...
    method.basisCondition <= conditionGate;
preconditioningOk = method.preconditioning.Credible;
accepted = scoreOk && conditionOk && preconditioningOk;
confidence = mean([double(scoreOk), double(conditionOk), ...
    double(preconditioningOk)]);
reason = sprintf(['single-valuedness %.3g, condition %.3g, ' ...
    'precondition %s'], method.score, method.basisCondition, ...
    method.preconditioning.Reason);
parameters = sprintf(['R=%.6g ohm, lambda score=%.3g, degree=%d, ' ...
    'v0=%.3g, i0=%.3g'], method.R, method.score, max(method.orders), ...
    method.preconditioning.VOffset, method.preconditioning.IOffset);

candidate = sp1_candidate_result(struct( ...
    'Name', 'flux_curve', ...
    'Family', 'nonlinear_storage', ...
    'PhysicalMeaning', 'single-valued storage lambda=f(i)', ...
    'Accepted', accepted, ...
    'Confidence', confidence, ...
    'Coverage', NaN, ...
    'ResidualOrScore', method.score, ...
    'StabilityCV', NaN, ...
    'Complexity', numel(method.orders) + 1, ...
    'Parameters', parameters, ...
    'Reason', reason, ...
    'Method', method, ...
    'Diagnostics', struct('basisCondition', method.basisCondition, ...
    'preconditioning', method.preconditioning)));

end
