function candidate = sp1_candidate_lti_parallel_rl(data, config, opts, decisionOpts)
%SP1_CANDIDATE_LTI_PARALLEL_RL Candidate wrapper for parallel R-L.

if nargin < 3
    opts = struct();
end
if nargin < 4
    decisionOpts = struct();
end

method = sp1_identify_windowed_parallel_rl(data, config, opts);
W = method.windows;
valid = W.Valid > 0;
stabilityCV = max([sp1_robust_cv(W.G(valid)), ...
    sp1_robust_cv(W.Gamma(valid))]);

coverageGate = nv3_get_option(decisionOpts, 'coverageGate', 0.80);
residualGate = nv3_get_option(decisionOpts, 'residualGate', 2e-2);
stabilityGate = nv3_get_option(decisionOpts, 'stabilityGate', 0.15);

coverageOk = method.summary.ValidCoverage >= coverageGate;
residualOk = method.summary.MedianPowerResidual <= residualGate;
stableOk = stabilityCV <= stabilityGate;
accepted = coverageOk && residualOk && stableOk;
confidence = mean([double(coverageOk), double(residualOk), double(stableOk)]);
reason = sprintf('coverage %.2f, residual %.3g, stabilityCV %.3g', ...
    method.summary.ValidCoverage, method.summary.MedianPowerResidual, ...
    stabilityCV);
parameters = sprintf('G=%.6g S, R=%.6g ohm, Gamma=%.6g 1/H, L=%.6g H', ...
    method.summary.MedianG, method.summary.MedianR, ...
    method.summary.MedianGamma, method.summary.MedianL);

candidate = sp1_candidate_result(struct( ...
    'Name', 'lti_parallel_rl', ...
    'Family', 'lti_windowed', ...
    'PhysicalMeaning', 'parallel R-L: i = G v + Gamma int(v)dt', ...
    'Accepted', accepted, ...
    'Confidence', confidence, ...
    'Coverage', method.summary.ValidCoverage, ...
    'ResidualOrScore', method.summary.MedianPowerResidual, ...
    'StabilityCV', stabilityCV, ...
    'Complexity', 2, ...
    'Parameters', parameters, ...
    'Reason', reason, ...
    'Method', method, ...
    'Diagnostics', struct('validWindows', sum(valid), ...
    'windowCount', height(W))));

end
