function candidate = sp1_candidate_lti_parallel_series_rl(data, config, opts, decisionOpts)
%SP1_CANDIDATE_LTI_PARALLEL_SERIES_RL Candidate for R || (Rs+L).

if nargin < 3
    opts = struct();
end
if nargin < 4
    decisionOpts = struct();
end

method = sp1_identify_windowed_parallel_series_rl(data, config, opts);
W = method.windows;
valid = W.Valid > 0;
stabilityCV = max([sp1_robust_cv(W.Gp(valid)), ...
    sp1_robust_cv(W.Rs(valid)), sp1_robust_cv(W.L(valid))]);

coverageGate = nv3_get_option(decisionOpts, 'coverageGate', 0.80);
residualGate = nv3_get_option(decisionOpts, 'residualGate', 2e-2);
equationResidualGate = nv3_get_option(decisionOpts, ...
    'equationResidualGate', residualGate);
stabilityGate = nv3_get_option(decisionOpts, 'stabilityGate', 0.15);

coverageOk = method.summary.ValidCoverage >= coverageGate;
residualOk = method.summary.MedianPowerResidual <= residualGate;
equationOk = method.summary.MedianEquationResidual <= equationResidualGate;
stableOk = stabilityCV <= stabilityGate;
accepted = coverageOk && residualOk && equationOk && stableOk;
confidence = mean([double(coverageOk), double(residualOk), ...
    double(equationOk), double(stableOk)]);
reason = sprintf(['coverage %.2f, equation residual %.3g, ' ...
    'power residual %.3g, stabilityCV %.3g'], ...
    method.summary.ValidCoverage, method.summary.MedianEquationResidual, ...
    method.summary.MedianPowerResidual, stabilityCV);
parameters = sprintf(['Rp=%.6g ohm, Gp=%.6g S, Rs=%.6g ohm, ' ...
    'L=%.6g H'], method.summary.MedianRp, method.summary.MedianGp, ...
    method.summary.MedianRs, method.summary.MedianL);

candidate = sp1_candidate_result(struct( ...
    'Name', 'lti_parallel_series_rl', ...
    'Family', 'lti_windowed', ...
    'PhysicalMeaning', ...
    'parallel resistor with real inductor branch: R_p || (R_s + L)', ...
    'Accepted', accepted, ...
    'Confidence', confidence, ...
    'Coverage', method.summary.ValidCoverage, ...
    'ResidualOrScore', method.summary.MedianPowerResidual, ...
    'StabilityCV', stabilityCV, ...
    'Complexity', 3, ...
    'Parameters', parameters, ...
    'Reason', reason, ...
    'Method', method, ...
    'Diagnostics', struct('validWindows', sum(valid), ...
    'windowCount', height(W), ...
    'medianEquationResidual', method.summary.MedianEquationResidual)));

end
